In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("cars_1")
df2=pd.read_csv("cars_2")

In [3]:
df.head()

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
0,0,All cars / AC / ACE / 3.5 i V8 32V Turbo (354...,Petrol,3506,8,264,5.5,250,4420,1870,1300,1510,n/d
1,1,All cars / AC / ACE / 4.6 i V8 32V (326 Hp),Petrol,4601,8,243,5.7,250,4420,1870,1300,1510,n/d
2,2,All cars / AC / ACE / 4.9 i V8 (260 Hp),Petrol,4942,8,194,0,225,4420,1870,1300,1440,8.6 l/100km
3,3,0,0,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
df2.head()

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
0,0,All cars / Mercedes-Benz / 190 / 1.8 i (109 Hp),Petrol,1797,4,81,12.2 (13),185 (180 ),4450,1690,1375,1160 /1660,8.7 l/100km
1,1,All cars / Mercedes-Benz / 190 / 1.7 i (107 Hp),Petrol,1737,4,80,12.3 (13),185 (180 ),4450,1690,1375,1170 /1720,8.7 l/100km (9.3 l/100km)
2,2,0,0,0,0,0,0,0,0,0,0,0,0
3,3,All cars / Mercedes-Benz / 190 / 2.5 i 16V (1...,Petrol,2498,4,145,7.7,230,4450,1690,1375,1300 /1800,9 l/100km
4,4,All cars / Mercedes-Benz / 190 / 2.5 D (94 Hp),Diesel,2497,5,70,15.1 (16.1),174 (170 ),4450,1690,1375,1250 /1750,7.1 l/100km (7.7 l/100km)

In [5]:
d=[df,df2]
data=pd.concat(d)
df3=data.sample(frac=1).reset_index(drop=True)

In [6]:
df3.head()

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
0,6368,All cars / Skoda / Octavia / RS 2.0 TSI (220 ...,Petrol,1984,4,164,6.9,245,4685,1814,1461,1445 /1912,6.4 l/100km
1,7679,All cars / Toyota / Corolla / 1.6 i 16V VVT-i...,Petrol,1598,4,92,10.4,195,4540,1760,1470,1300 /1785,6.9 l/100km
2,10631,All cars / Volvo / XC60 / 2.4 D5 (215 Hp),Diesel,2400,5,160,8.1,n/d,4627,1891,1713,1794 /2505,5.7 l/100km
3,7112,All cars / Suzuki / Wagon R+ / 1.0 i 12V (53 Hp),Petrol,993,3,40,0,132,3500,1620,1705,1015 /1415,n/d
4,4058,All cars / Peugeot / 308 / 1.6I HDi FAP (90Hp...,Diesel,1560,4,67,13,180,4276,1815,1498,1387 /1840,4.7 l/100km

In [7]:
df3.shape

(19983, 13)

In [8]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19983 entries, 0 to 19982
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       19983 non-null  int64
 1   name             19983 non-null  object
 2   fuel             19983 non-null  object
 3   engine_capacity  19983 non-null  object
 4   cylinder         19983 non-null  object
 5   kw               19983 non-null  object
 6   acceleration     19983 non-null  object
 7   max_speed        19983 non-null  object
 8   lenght           19983 non-null  object
 9   width            19983 non-null  object
 10  height           19983 non-null  object
 11  weight           19983 non-null  object
 12  consump          19983 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.0+ MB

In [9]:
df3.isnull().sum()

Unnamed: 0         0
name               0
fuel               0
engine_capacity    0
cylinder           0
kw                 0
acceleration       0
max_speed          0
lenght             0
width              0
height             0
weight             0
consump            0
dtype: int64

### Cleaning data

In [10]:
#droping rows with 0 value
df4=df3[df3["name"]!="0"]
df4.shape

(14835, 13)

In [11]:
df4.sample(20)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
12086,2397,All cars / BMW / 5er / 530 i (231 Hp),Petrol,2979,6,172,6.9 (7.1),250 (240 ),4841,1846,1464,1570 /2055,9.5 l/100km (9.9 l/100km)
15704,3344,All cars / Chevrolet / Suburban / 5.3 i V8 4W...,Petrol,5300,8,224,0,156,5570,2002,1887,2440 /3265,n/d
18076,6297,All cars / Skoda / Fabia / 1.4 (68 Hp),Petrol,1397,4,51,15.4,162,4222,1646,1449,1065 /1550,6.9 l/100km
9289,3069,All cars / Opel / Frontera / 2.5 TDS (115 Hp),Diesel,2499,4,86,16,155,4192,1780,1721,1828 /2510,10.4 l/100km
4947,7126,All cars / Honda / Z / 0.7 12V (52 Hp),Petrol,656,3,39,0,130,3395,1475,1675,960 /1180,n/d
16110,6887,All cars / Subaru / WRX / 2.5 (300 Hp) Turbo AT,Petrol,2457,4,224,6,245,4415,1795,1470,1525,10.6 l/100km
13085,3420,All cars / Chevrolet / Trax / 1.7D (130 Hp) AT,Diesel,1686,4,97,10.5,182,4248,1776,1674,1387 /1891,5.3 l/100km
10011,6557,All cars / GMC / Yukon / 4.8 i V8 16V 4WD (29...,n/d,4807,8,219,0,n/d,5130,2007,1955,2570 /3311,n/d
2210,5960,All cars / Seat / Ibiza / 1.2 TSI (105 Hp) Ec...,Petrol,1197,4,78,9.8,190,4043,1693,1428,1095 /1546,5.1 l/100km
13155,8377,All cars / Land Rover / Freelander / 2.0 DI (...,Diesel,1994,4,73,15.2,155,4380,1805,1760,1405 /2050,n/d
11541,6303,All cars / Ford / Sierra / 1.3 (60 Hp),n/d,n/d,n,d,0,n/d,4425,1694,1407,n/d,n/d
15848,5355,All cars / Ford / C-MAX / 2.0 Duratorq TDCi (...,Diesel,n/d,n,104,10.1,200,n/d,1828,1684,1575 /2300,5.1 l/100km
8320,7167,All cars / Hyundai / Accent / 1.5 i 16V GT (9...,Petrol,1495,4,74,0,n/d,n/d,n/d,n/d,n/d,n/d
14012,3197,All cars / Chevrolet / Cruze / 2.0 TD (163 Hp),Diesel,1998,4,122,8.5,210,4603,1797,1477,1460 /1998,4.8 l/100km
6749,2410,All cars / BMW / 5er / 525 i (218 Hp),Petrol,2497,6,163,7.8,240,4843,1846,1491,1570 /2165,n/d
1843,5738,All cars / Ford / Focus / 1.0 EcoBoost (125 Hp),Petrol,998,3,93,11.2,193,4556,1823,1505,1518 /1900,5 l/100km
10528,7737,All cars / Toyota / Corolla / 1.6 i 16V Si (1...,Petrol,1587,4,85,10,195,4095,1685,1380,1067 /1595,7.3 l/100km
4874,692,All cars / Mercedes-Benz / E-class / E 320 T ...,Petrol,3199,6,167,9.2,225,4839,1799,1505,1740 /2360,n/d
19817,6406,All cars / Skoda / Octavia / 2.0 TDI PD (140 Hp),Diesel,1968,4,104,9.6 (9.6),208 (209 ),4572,1769,1462,1335 /1995,n/d
17509,6830,All cars / Honda / Civic / 1.8 i 16V (140 Hp),Petrol,1798,4,104,9.2 (10.6),200 (200 ),4545,1750,1435,1194 /1675,6.5 l/100km (7.3 l/100km)

In [12]:
df4["fuel"].value_counts()

Petrol                9649
Diesel                3742
Fuel system            924
n/d                    508
Petrol/Electricity       8
Electricity              4
Name: fuel, dtype: int64

In [13]:
#keeping only cars on petrol and diesel
list_f = ["Petrol","Diesel"]
df5 = df4[df4["fuel"].isin(list_f)]

In [14]:
df5.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
15657,6261,All cars / Ford / Sierra / 2.0 i (120 Hp),Petrol,1998,4,89,0,n/d,4425,1694,1407,n/d,n/d
14786,7391,All cars / Hyundai / Pony / 1.3 (72 Hp),Petrol,1299,4,54,0,155,4100,1605,1365,920,7.7 l/100km
602,3371,All cars / Chevrolet / Tahoe / 5.3 i V8 4WD (...,Petrol,5328,8,204,12,170,5052,2068,1960,2419 /3084,15.4 l/100km
3838,3307,All cars / Chevrolet / Rezzo / 2.0 i 16V (121...,Petrol,1998,4,90,10.3 (11.7),180 (173 ),4350,1755,1580,1306 /1862,9 l/100km (10.8 l/100km)
18372,1986,All cars / Nissan / March / 1.2 i 16V (80 Hp),Petrol,1240,4,60,13.9 (17.9),167 (145 ),3715,1660,1525,970 /1475,5.9 l/100km (6.6 l/100km)
3821,637,All cars / Mercedes-Benz / E-class / E 240 4 ...,Petrol,2597,6,132,10.8,214,4850,1822,1496,1745 /2390,10.9 l/100km
9440,7181,All cars / Hyundai / Atos / 1.0 i (56 Hp),Petrol,999,4,42,16.5,142,3495,1495,1580,930 /1220,n/d
10256,4198,All cars / Peugeot / 407 / 3.0 i V6 24V (211 Hp),Petrol,2946,6,157,8.4 (8.7),243 (235 ),4815,1868,1399,1687 /2020,8.5 l/100km (8.5 l/100km)
12006,7977,All cars / Toyota / Hilux / 2.8 D (91 Hp),Diesel,2779,4,68,0,n/d,4435,1690,1750,n/d,n/d
17753,149,All cars / Mercedes-Benz / A-class / A 170 CD...,Diesel,1689,4,67,12 (13.7),175 (172 ),3575,1719,1590,1100 /1560,n/d

In [15]:
df5.shape

(13391, 13)

In [16]:
df5["fuel"].value_counts()

Petrol    9649
Diesel    3742
Name: fuel, dtype: int64

In [17]:
df6=df5[df5["engine_capacity"]!="n/d"]

In [18]:
df6.shape

(13155, 13)

In [19]:
df7=df6.copy()

In [20]:
#converting into float
df7["engine_capacity"]=df6["engine_capacity"].astype(int)

In [21]:
df7["cylinder"].unique()

array(['4', '5', '3', '6', '8', '1', 'n', '2'], dtype=object)

In [22]:
df8=df7[df7["cylinder"]!="n"]

In [23]:
df8.shape

(13092, 13)

In [24]:
df9=df8.copy()

In [25]:
df9["cylinder"]=df8["cylinder"].astype(int)

In [26]:
df10=df9[df9["kw"]!="d"]

In [27]:
df10.shape

(13081, 13)

In [28]:
df11=df10.copy()

In [29]:
df11["kw"]=df10["kw"].astype(int)

In [30]:
df11["acceleration"].value_counts()

0              2641
11              191
9.5             169
8.5             165
10.5            164
               ...
13.5 (13.5)       1
7.8 (8.9)         1
5.2 (5.1)         1
13.2 (17)         1
6.5 (7.9)         1
Name: acceleration, Length: 1007, dtype: int64

In [31]:
df12=df11[df11["acceleration"]!="0"]

In [32]:
df12.shape

(10440, 13)

In [33]:
df13=df12.copy()

In [34]:
df13["acceleration"]=df12["acceleration"].apply(lambda x: x.replace("(","").replace(")",""))

In [35]:
df13.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
5469,9501,All cars / Volkswagen / Lupo / 1.6 i 16V GTI ...,Petrol,1598,4,93,8.2,205,3527,1640,1460,980 /1320,7 l/100km
11889,2622,All cars / Opel / Astra / 1.7 CDTI (130 Hp) E...,Diesel,1686,4,97,11.4,198,4698,1814,1535,n/d,4 l/100km
10218,2014,All cars / BMW / 3er / 320d (163 Hp) Efficien...,Diesel,1995,4,122,8,230,4624,1811,1429,1495 /1970,4.1 l/100km
4144,695,All cars / Mercedes-Benz / E-class / E 280 T ...,Petrol,2799,6,152,9.5,225,4839,1799,1505,1630 /2280,n/d
16726,5449,All cars / Rover / 400 / 2.0 i (136 Hp),Petrol,1994,4,101,8.7,200,4365,1680,1390,1210 /1650,8 l/100km
18451,3035,All cars / Opel / Corsa / 1.5 TD (67 Hp),Diesel,1488,4,50,14,165,3729,1610,1420,950 /1445,5.7 l/100km
693,3169,All cars / Chevrolet / Corvette / 5.7 i V8 16...,Petrol,5665,8,265,5.3,260,4564,1869,1212,1535 /1745,n/d
14277,4788,All cars / Renault / 19 / 1.8 i 16V (136 Hp),Petrol,1794,4,101,8.5,212,4162,1696,1412,1115 /1580,8.2 l/100km
8843,3915,All cars / Peugeot / 301 / 1.6 HDI (92 Hp),Diesel,1560,4,69,12.4,180,4442,1748,1466,1090 /1549,4.1 l/100km
6309,2284,All cars / BMW / 5er / 550i (450 Hp) Steptronic,Petrol,4395,8,336,5,250,5004,1901,1559,2145 /2670,9.2 l/100km

In [36]:
def converting(x):
    tokens=x.split(" ") #splitting on " "
    if len (tokens)== 2:
        return (float(tokens[0])+float(tokens[1]))/2 #returning average values
    try:
        return float(x) #return float
    except:
        return None #ignore value that is not float

In [37]:
df14=df13.copy()

In [38]:
df14["acceleration"]=df13["acceleration"].apply(converting)

In [39]:
df14.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
8519,9100,All cars / Mazda / Millenia / 2.3 i V6 (213 Hp),Petrol,2255,6,159,8.5,222,4821,1770,1395,1560 /1985,n/d
18687,2255,All cars / Nissan / Qashqai / 1.6 (117 Hp) ECO,Petrol,1598,4,87,11.9,181,4330,1780,1615,1312 /1830,5.9 l/100km
7758,5703,All cars / Ford / Fiesta / 1.6 i (110 Hp),Petrol,1598,4,82,9.8,192,3743,1606,1379,845 /1325,7.8 l/100km
8507,7206,All cars / Hyundai / Elantra / 2.0i AT (143 Hp),Petrol,1975,4,107,10.5,190,4505,1775,1480,1221 /1730,n/d
463,9534,All cars / Volkswagen / Passat / 2.0 TDI (140...,Diesel,1968,4,104,9.8,214,4802,1855,1421,1550 /1970,4.6 l/100km
15223,8270,All cars / Lancia / Phedra / 2.2 JTD (128 Hp),Diesel,2179,4,95,12.6,182,4750,1863,1760,1710 /2505,7.4 l/100km
12997,4953,All cars / Renault / Clio / 1.4 16V (B/CB0L) ...,Petrol,1390,4,73,10.7,185,3773,1640,1417,965 /1495,7.3 l/100km
494,2330,All cars / BMW / 5er / 520d (190 Hp) xDrive S...,Diesel,1995,4,142,8.2,220,4907,1860,1462,1840 /2480,5.1 l/100km (5.4 l/100km)
13901,8002,All cars / Kia / Pride / 1.3 i (64 Hp),Petrol,1324,4,48,13.7,159,3565,1605,1450,825 /1310,n/d
15971,10012,All cars / Volkswagen / Touareg / 3.0 TDI (24...,Diesel,2967,6,179,8.0,207,4754,1928,1726,2350 /2945,9.6 l/100km

In [40]:
df14["max_speed"]=df13["max_speed"].apply(lambda x:x.replace("(","").replace(" )","").replace("",""))

In [41]:
df14.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
2537,3606,All cars / Opel / Vectra / 1.8 ECOTEC (122 Hp),Petrol,1796,4,91,11.2,205,4596,1798,1460,1315 /1865,7.9 l/100km
7289,3548,All cars / Opel / Signum / 2.2 i 16V ECOTEC (...,Petrol,2198,4,116,10.4,211 206,4636,1798,1466,1535 /2050,8.1 l/100km (9.1 l/100km)
1075,8485,All cars / Lexus / SC / 430 (285 Hp),Petrol,4293,8,213,6.4,250,4515,1825,1370,1815 /2110,12 l/100km
13559,1639,All cars / Audi / Q7 / 4.2 FSI (350 Hp) quatt...,Petrol,4163,8,261,7.4,244,5086,1983,1737,2315 /2965,13.3 l/100km
5913,8254,All cars / Lancia / Lybra / 1.8 16V (131 Hp),Petrol,1747,4,98,10.3,201,4466,1743,1462,1300 /1820,8.3 l/100km
3988,4274,All cars / Peugeot / 505 / 2.5 Diesel (75 Hp),Diesel,2498,4,56,19.5,146,4900,1730,1540,1375 /2055,9 l/100km
4093,2436,All cars / Nissan / Terrano / 2.7 TD 4WD (99 Hp),Diesel,2663,4,74,18.0,150,4365,1690,1680,1670 /2300,10.3 l/100km
706,247,All cars / Mercedes-Benz / C-class / C 220 CD...,Diesel,2148,4,127,7.6,229,4581,1770,1447,1585 /2070,6.1 l/100km
19216,9131,All cars / Mazda / Mx-5 / 1.6 (90 Hp),Petrol,1598,4,67,10.6,175,3975,1675,1230,981 /1230,8.7 l/100km
5640,5089,All cars / Fiat / Punto / 1.6 16V Multijet (1...,Diesel,1598,4,89,9.6,193,4065,1687,1490,1190,4.5 l/100km

In [42]:
df15=df14[df14["max_speed"]!="n/d"]

In [43]:
def convert(x):
    tokens=x.split(" ") #splitting on " "
    if len (tokens)== 3:
        return (int(tokens[0])+int(tokens[2]))/2 #returning average values
    try:
        return float(x) #return float
    except:
        return None #ignore value that is not float

In [44]:
df16=df15.copy()

In [45]:
df16["max_speed"]=df15["max_speed"].apply(convert)

In [46]:
df16.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump
11110,2963,All cars / Cadillac / STS / 4.6 i V8 32V VVT ...,Petrol,4565,8,242,7.0,248.0,4985,1843,1464,1920,n/d
917,3856,All cars / Peugeot / 206 / 1.1 i (60 Hp),Petrol,1124,4,45,15.2,158.0,3835,1652,1426,910 /1405,n/d
11826,3500,All cars / Chrysler / LE Baron / 3.0 i V6 (14...,Petrol,2972,6,107,11.5,185.0,4695,1740,1300,1370,8.4 l/100km
15136,1443,All cars / Audi / A6 / 2.8 30V (193 Hp),Petrol,2771,6,144,8.4,231.0,4796,1810,1479,1510 /2090,10 l/100km (9.8 l/100km)
13637,7368,All cars / Toyota / Altezza / 3.0 i 24V (220 Hp),Petrol,2997,6,164,8.5,230.0,4400,1725,1420,1510 /1955,n/d
12943,5524,All cars / Ford / Escort / 1.8 16V XR3i (130 Hp),Petrol,1798,4,97,8.0,197.0,n/d,n/d,n/d,1025,8.5 l/100km
14591,2312,All cars / BMW / 5er / 525d (218 Hp) xDrive S...,Diesel,1995,4,163,7.3,231.0,4907,1860,1462,1945 /2480,5.8 l/100km (5.4 l/100km)
602,3371,All cars / Chevrolet / Tahoe / 5.3 i V8 4WD (...,Petrol,5328,8,204,12.0,170.0,5052,2068,1960,2419 /3084,15.4 l/100km
4846,5467,All cars / Rover / 45 / 2.0 TD (101 Hp),Diesel,1994,4,75,10.6,185.0,4517,1696,1394,1305 /1720,5.4 l/100km
10345,1491,All cars / Audi / A6 / 1.9 TDI (75 Hp),Diesel,1896,4,56,18.3,160.0,4595,1720,1445,1355 /1790,6.6 l/100km

In [47]:
df16.shape

(10219, 13)

In [48]:
df17=df16[df16["lenght"]!="n/d"]

In [49]:
df18=df17[df17["width"]!="n/d"]

In [50]:
df19=df18[df18["height"]!="n/d"]

In [51]:
df20=df19[df19["weight"]!="n/d"]

In [52]:
df21=df20[df20["consump"]!="n/d"]

In [53]:
df21.shape

(7381, 13)

In [54]:
df22=df21.copy()

In [55]:
df22["car_brand"]=df21["name"].apply(lambda x: x.split("/")[1].strip())
df22.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump,car_brand
12654,8704,All cars / Mazda / 2 / 1.3 (75 Hp),Petrol,1349,4,56,14.00,168.0,3900,1695,1475,960 /1485,5.1 l/100km,Mazda
17552,6833,All cars / Honda / Civic / 1.8 i 16V (140 Hp) AT,Petrol,1798,4,104,10.90,207.0,4250,1760,1460,1250 /1750,6.5 l/100km,Honda
16213,6136,All cars / Seat / Leon / 1.8 T 20V 4 (180 Hp),Petrol,1781,4,134,7.80,224.0,4184,1742,1457,1464 /1912,9.6 l/100km,Seat
12141,9940,All cars / Volkswagen / Scirocco / 2.0 (170 H...,Diesel,1968,4,127,8.10,220.0,4256,1810,1404,1421 /1800,5.5 l/100km,Volkswagen
12907,1437,All cars / Audi / A6 / 1.8 T (150 Hp),Petrol,1781,4,112,9.85,213.0,4796,1810,1452,1490 /2040,8.5 l/100km (8.5 l/100km),Audi
18944,9399,All cars / Volkswagen / Jetta / 1.6i 16V (102Hp),Petrol,1595,4,76,12.20,186.0,4554,1781,1459,1343 /1870,7.4 l/100km,Volkswagen
18754,726,All cars / Mercedes-Benz / E-class / E 320 (1...,Petrol,3199,6,164,8.30,235.0,4655,1740,1395,1490 /1980,11 l/100km,Mercedes-Benz
3164,1764,All cars / Nissan / 370Z / 3.7 (328 Hp),Petrol,3696,6,245,5.30,250.0,4250,1845,1315,1525 /1800,10.6 l/100km,Nissan
7154,9123,All cars / Volkswagen / Eos / 2.0 i 16V FSI (...,Petrol,1984,4,112,9.80,210.0,4407,1791,1443,1481 /1950,8.2 l/100km,Volkswagen
13086,5572,All cars / Saab / 9-3 / 2.0 t (150 Hp) AT,Petrol,1998,4,112,10.70,205.0,4635,1762,1466,1440 /1970,8.2 l/100km,Saab

In [56]:
df23=df22.copy()

In [57]:
df23["car_brand"]=df22["name"].apply(lambda x: x.split("/")[1].strip())
df23.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump,car_brand
208,4615,All cars / Dodge / Nitro / 3.7 i V6 12V 4 WD ...,Petrol,3701,6,159,10.30,190.0,4584,1856,1755,1875 /2540,12.1 l/100km,Dodge
5944,9137,All cars / Volkswagen / Golf / 2.0 TDI (150 H...,Diesel,1968,4,112,8.90,216.0,4562,1799,1481,1454 /1990,4.5 l/100km,Volkswagen
15594,5289,All cars / Fiat / Tipo / 1.1 (160.AA) (56 Hp),Petrol,1108,4,42,17.20,150.0,3958,1700,1450,905,6.7 l/100km,Fiat
9747,3200,All cars / Chevrolet / Cruze / 1.4 (140 Hp),Petrol,1362,4,104,9.30,200.0,4603,1797,1477,1335 /1873,5.7 l/100km,Chevrolet
19810,6504,All cars / Geo / Metro / 1.0 (55 Hp),Petrol,993,3,41,20.00,140.0,3745,1575,1330,750,4.9 l/100km,Geo
18997,5860,All cars / Ford / Focus / 1.8 DI (75 Hp),Diesel,1753,4,56,14.70,168.0,4152,1698,1430,1183 /1685,5.1 l/100km,Ford
13931,4204,All cars / Peugeot / 407 / 2.0 i 16V (136 Hp),Petrol,1997,4,101,11.25,209.0,4675,1811,1447,1415 /1998,8.2 l/100km (8.7 l/100km),Peugeot
13039,2446,All cars / BMW / 5er / 540 i (286 Hp),Petrol,3982,8,213,6.40,250.0,4720,1751,1417,1680 /2230,12.7 l/100km,BMW
4155,10035,All cars / Volkswagen / Touran / 2.0 TDI (140...,Diesel,1968,4,104,10.60,195.0,4391,1794,1652,1561 /2210,6.5 l/100km,Volkswagen
16370,3207,All cars / Chevrolet / Cruze / 1.6 (124 Hp),Petrol,1598,4,92,12.60,191.0,4681,1797,1521,1360 /1895,6.4 l/100km,Chevrolet

In [58]:
df24=df23.copy()

In [59]:
df24["car_model"]=df23["name"].apply(lambda x: x.split("/")[2].strip())

In [60]:
def conv(x):
    tokens=x.split("/") #splitting on "-"
    if len (tokens)==2:
        return (int(tokens[0])+int(tokens[1]))/2 #returning average values
    try:
        return float(x) #return float
    except:
        return None #ignore value that is not float

In [61]:
df25=df24.copy()

In [62]:
df25["weight"]=df24["weight"].apply(conv)

In [63]:
df25.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump,car_brand,car_model
13391,856,All cars / Mercedes-Benz / S-class / S 600 L ...,Petrol,5513,1,373,4.9,250.0,5163,1855,1444,2362.5,14.8 l/100km,Mercedes-Benz,S-class
15863,9623,All cars / Volkswagen / Passat / 2.3 i VR 20V...,Petrol,2324,5,127,9.6,224.0,4703,1746,1462,1777.5,9.6 l/100km,Volkswagen,Passat
18147,9198,All cars / Volkswagen / Golf / 1.6 (102 Hp) AT,Petrol,1595,4,76,12.5,181.0,4199,1779,1479,1501.0,8.1 l/100km,Volkswagen,Golf
271,3571,All cars / Chrysler / Stratus / 2.0 LE (131 Hp),Petrol,1996,4,98,10.9,205.0,4746,1822,1374,1605.5,8.5 l/100km,Chrysler,Stratus
4814,2176,All cars / BMW / 3er / 318 i (115 Hp),Petrol,1796,4,86,12.5,194.0,4433,1710,1348,1555.0,7.9 l/100km,BMW,3er
4540,5139,All cars / Fiat / Punto / 1.4 GT Turbo (136 Hp),Petrol,1372,4,101,7.5,213.0,3770,1625,1460,1213.0,8 l/100km,Fiat,Punto
19679,7688,All cars / Jaguar / XF / 3.0 V6 D (240 Hp),Diesel,2993,6,179,7.1,240.0,4961,1877,1460,2090.0,6.8 l/100km,Jaguar,XF
18943,6021,All cars / Seat / Ibiza / 2.0 i (115 Hp),Petrol,1984,4,86,9.3,195.0,3813,1640,1408,1242.5,7.6 l/100km,Seat,Ibiza
14053,959,All cars / Audi / A3 / 1.8 TFSI (160 Hp),Petrol,1798,4,119,8.2,220.0,4292,1765,1423,1662.5,6.7 l/100km,Audi,A3
8950,9832,All cars / Volkswagen / Polo / 1.6 (105 Hp) T...,Petrol,1598,4,78,11.3,187.0,3897,1650,1465,1372.5,7.4 l/100km,Volkswagen,Polo

In [64]:
df26=df25.copy()

In [65]:
df26["fuel_consumption"]=df25["consump"].apply(lambda x: x.split(" ")[0].strip())

In [66]:
df26.sample(10)

,Unnamed: 0,name,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,consump,car_brand,car_model,fuel_consumption
8327,5818,All cars / Ford / Focus / 1.6 Duratec 16V (10...,Petrol,1596,4,75,11.9,180.0,4342,1840,1497,1476.0,6.7 l/100km,Ford,Focus,6.7
2374,3550,All cars / Opel / Signum / 2.0 i 16V Turbo EC...,Petrol,1998,4,130,9.4,220.0,4636,1798,1466,1817.5,9.2 l/100km,Opel,Signum,9.2
3543,8205,All cars / Toyota / RAV 4 / 1.8 VVTi (3 dr) (...,Petrol,1794,4,93,12.2,175.0,3805,1735,1670,1397.5,7.4 l/100km,Toyota,RAV 4,7.4
4933,2262,All cars / BMW / 4er / 435i (306 Hp),Petrol,2979,6,228,5.6,250.0,4638,1825,1384,1980.0,8.1 l/100km,BMW,4er,8.1
13955,10414,All cars / Volvo / S80 / T6 (304 Hp) AWD,Petrol,2953,6,227,6.4,250.0,4854,1907,1493,1859.5,9.9 l/100km,Volvo,S80,9.9
9452,9222,All cars / Volkswagen / Golf / 2.0 SDI (75 Hp),Diesel,1968,4,56,16.7,163.0,4204,1759,1485,1541.0,5.4 l/100km,Volkswagen,Golf,5.4
12605,3823,All cars / Citroen / C5 / 2.0i 16V (143 Hp) A...,Petrol,1997,4,107,11.0,205.0,4779,1860,1451,1836.5,8.9 l/100km,Citroen,C5,8.9
16093,2311,All cars / BMW / 5er / 530d (258 Hp) xDrive S...,Diesel,2993,6,192,5.9,248.0,4907,1860,1462,2262.5,6 l/100km (5.7 l/100km),BMW,5er,6
12561,6769,All cars / Subaru / Justy / 1000 4WD (KAD-A) ...,Petrol,997,3,37,17.3,140.0,3695,1535,1420,1037.5,7.5 l/100km,Subaru,Justy,7.5
7992,2665,All cars / BMW / X1 / sDrive 20d (184 Hp) Ste...,Diesel,1995,4,137,7.7,218.0,4477,1798,1545,1817.5,5 l/100km,BMW,X1,5

In [67]:
data=df26.drop(["Unnamed: 0","name","consump"],axis=1)

In [68]:
data_2 = data.reindex(columns=['car_brand','car_model', 'fuel', 'engine_capacity', 'cylinder', 'kw',
       'acceleration', 'max_speed', 'lenght', 'width', 'height', 'weight', 'fuel_consumption'])

In [69]:
data_2.sample(10)

,car_brand,car_model,fuel,engine_capacity,cylinder,kw,acceleration,max_speed,lenght,width,height,weight,fuel_consumption
10593,Innocenti,Elba,Petrol,1581,4,57,12.00,168.0,4037,1555,1450,1180.0,7.6
5707,Volkswagen,Polo,Diesel,1598,4,56,14.00,170.0,3970,1682,1485,1358.5,4.2
19400,Ford,Mondeo,Diesel,2179,4,130,8.70,223.0,4844,1886,1500,1825.5,6.2
71,Honda,Legend,Petrol,3471,6,220,7.30,250.0,4957,1845,1450,1860.0,11.9
11817,Mercedes-Benz,A-class,Diesel,1991,4,104,9.55,198.5,3838,1764,1595,1572.5,5.4
7766,BMW,3er,Petrol,2996,6,203,6.10,250.0,4520,1817,1421,1747.5,8.7
7409,Subaru,Forester,Petrol,1994,4,112,9.70,197.0,4485,1735,1590,1635.0,9.3
9764,Audi,S8,Petrol,4172,8,268,5.40,250.0,5034,1880,1418,2030.0,13
16297,Saab,9-3,Petrol,1998,4,157,8.25,232.5,4635,1762,1466,1725.0,8.5
591,Volkswagen,Golf,Petrol,1395,4,112,8.80,212.0,4338,1807,1578,1635.5,5.6

In [70]:
#saving csv file
data_2.to_csv("clean_cars",index=False)